### ISSUE TITLE
Don't break when a mentioned website doesn't respond

### ISSUE THREAD

**Issue by nhoizey** [aarongustafson/jekyll-webmention_io#61]
I have old posts on my blog, with links to sites that don't exist anymore.

When I run the `bundle exec jekyll webmention` command, it breaks when trying to send a mention to the first of these sites:

```shell
$ bundle exec jekyll webmention
Configuration file: _config.yml
jekyll 3.5.1 | Error:  Failed to open TCP connection to www.pinkfloyd-thewall.com:80 (getaddrinfo: nodename nor servname provided, or not known)
```

Can I change `false` to anything else in the `webmention_io_outgoing.yml` file, to make the command ignore this mention?

**Comment by aarongustafson** [comment]
I will take a look @ this.

**Comment by nhoizey** [comment]
Great, thanks!

**Comment by aarongustafson** [comment]
So, it's possible we might want to file this as a bug against the Webmention gem. I can make the calls isolated on my end but since I'm effectively outsourcing the Webmention action to that library, the fix should probably go there. It may even be a root issue in HTTParty or the Webmention gem’s implementation of it.

**Comment by nhoizey** [comment]
Ok, I didn't see you're using another gem for these actions.

**Comment by aarongustafson** [comment]
So sending webmentions looks like [it gets rescued](https://github.com/indieweb/mention-client-ruby/blob/master/lib/webmention/client.rb#L85), but checking for webmention support [does not have a blanket rescue](https://github.com/indieweb/mention-client-ruby/blob/master/lib/webmention/client.rb#L126). I'm curious to see if fixing that resolves the issue.

**Comment by aarongustafson** [comment]
I just did a `rescue` edit within GitHub. Can you test it?

**Comment by nhoizey** [comment]
I don't understand at all what this `rescue` is, but I will update the plugin and test… ;-)

**Comment by nhoizey** [comment]
It looks like it work, it doesn't stop anymore!

```
[jekyll-webmention_io] Endpoint lookup failed for http://www.pinkfloyd-thewall.com/: Failed to open TCP connection to www.pinkfloyd-thewall.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.pickpocknet.com/: Failed to open TCP connection to www.pickpocknet.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.mondinodejavu.com/: Failed to open TCP connection to www.mondinodejavu.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.palm.com/products/: Net::ReadTimeout
…
```

**Comment by aarongustafson** [comment]
Sweet. I can comment out the logging when I get back to my computer. Probably late tonight or tomorrow. Catching a flight shortly.

**Comment by nhoizey** [comment]
It didn't get to the end, I think:

```
[jekyll-webmention_io] Endpoint lookup failed for http://www.pinkfloyd-thewall.com/: Failed to open TCP connection to www.pinkfloyd-thewall.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.pickpocknet.com/: Failed to open TCP connection to www.pickpocknet.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.mondinodejavu.com/: Failed to open TCP connection to www.mondinodejavu.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.palm.com/products/: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://www.claudiaschiffer.com/store/: Failed to open TCP connection to www.claudiaschiffer.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.georgewbushstore.com/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.allocine-vision.com/: Failed to open TCP connection to www.allocine-vision.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.tous-contre-aol.ovh.org/: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://www.laverite-lefilm.com/: Failed to open TCP connection to www.laverite-lefilm.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.whatwomenwantmovie.com/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://solutions.journaldunet.com/0102/010221phpmychat.shtml>: bad URI(is not URI?): http://solutions.journaldunet.com/0102/010221phpmychat.shtml>
[jekyll-webmention_io] Endpoint lookup failed for http://phpmychat.sf.net/: HTTP redirects too deep
[jekyll-webmention_io] Endpoint lookup failed for http://www.habbohotel.com/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.imdb.com/Title?0162222: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://cyberie.webdo.ch/: Failed to open TCP connection to cyberie.webdo.ch:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.arpla.univ-paris8.fr/~spoutnik/fevrier/origine.htm: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.antisinistrose.com/: Failed to open TCP connection to www.antisinistrose.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.giraudy.fr/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.dauphin-affichage.com/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://lautre.org/communique.html: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://source.astralwerks.com/ram/air_beck.ram: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://marc.theaimsgroup.com/: Failed to open TCP connection to marc.theaimsgroup.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://marc.theaimsgroup.com/?l=pear-dev: Failed to open TCP connection to marc.theaimsgroup.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://marc.theaimsgroup.com/?l=pear-general: Failed to open TCP connection to marc.theaimsgroup.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.familiasalla-es.ro/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.guinnessstorehouse.com/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.tf1.fr/>: bad URI(is not URI?): http://www.tf1.fr/>
[jekyll-webmention_io] Endpoint lookup failed for http://www.webservices.org/: Failed to open TCP connection to www.webservices.org:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://ibm2.cicrp.jussieu.fr/bdej/DESS/DELANNOY/index.htm: Failed to open TCP connection to ibm2.cicrp.jussieu.fr:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://abcdrfc.free.fr/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.amazon.com/exec/obidos/ASIN/B00004HYCB/phpheaven: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.guinguettepirate.com/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.tarte-tatin.com/: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://www.transfert.net/fr/cyber_societe/article.cfm?idx_rub=87&idx_art=7284: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.transfert.net/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.colt-telecom.fr/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://usinfo.state.gov/regional/af/security/french/f0120605.htm: Failed to open TCP connection to usinfo.state.gov:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://usinfo.state.gov/francais/homepage.htm: Failed to open TCP connection to usinfo.state.gov:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://cvs.php.net/: Failed to open TCP connection to cvs.php.net:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://$user:$pass@$host/$db_name: Failed to open TCP connection to $host:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://username:password@protocol+hostspec/database: Failed to open TCP connection to protocol+hostspec:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://username:password@protocol+hostspec:110//usr/db_file.db: Failed to open TCP connection to protocol+hostspec:110 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://username:password@hostspec/database_name: Failed to open TCP connection to hostspec:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://username:password@hostspec: Failed to open TCP connection to hostspec:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://username@hostspec: Failed to open TCP connection to hostspec:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://hostspec/database: Failed to open TCP connection to hostspec:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://hostspec: Failed to open TCP connection to hostspec:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://With: Failed to open TCP connection to With:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://The: Failed to open TCP connection to The:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://Returns: Failed to open TCP connection to Returns:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://postgres@unix+localhost/clients_db': Failed to open TCP connection to unix+localhost:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://Here's: Failed to open TCP connection to Here's:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://After: Failed to open TCP connection to After:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://parameter: Failed to open TCP connection to parameter:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://examples: Failed to open TCP connection to examples:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.grenouille.com/>.: bad URI(is not URI?): http://www.grenouille.com/>.
[jekyll-webmention_io] Endpoint lookup failed for http://www.luccas.org/](http://www.luccas.org/: bad URI(is not URI?): http://www.luccas.org/](http://www.luccas.org/
[jekyll-webmention_io] Endpoint lookup failed for http://wwwusers.imaginet.fr/~jkounen/fr/longs/blueberry/main.htm: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.marilynmanson.net/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.spe.sony.com/movies/ghostsofmars/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.ghostofmars-lefilm.com/: Failed to open TCP connection to www.ghostofmars-lefilm.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.renault.fr/>: bad URI(is not URI?): http://www.renault.fr/>
[jekyll-webmention_io] Endpoint lookup failed for http://cvs.php.net/diff.php/php4/LICENSE?login=2&r1=1.17&r2=1.18&ty=h: Failed to open TCP connection to cvs.php.net:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://marc.theaimsgroup.com/?l=php-cvs&m=102727165608460&w=2: Failed to open TCP connection to marc.theaimsgroup.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://marc.theaimsgroup.com/?l=php-cvs&r=1&w=2: Failed to open TCP connection to marc.theaimsgroup.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://marc.theaimsgroup.com/?l=php-dev&m=102858914124505&w=2: Failed to open TCP connection to marc.theaimsgroup.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://marc.theaimsgroup.com/?l=php-dev&r=1&w=2: Failed to open TCP connection to marc.theaimsgroup.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://marc.theaimsgroup.com/?l=php-dev&m=102859018225314&w=2: Failed to open TCP connection to marc.theaimsgroup.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.advogato.org/person/mglazer/: HTTP redirects too deep
[jekyll-webmention_io] Endpoint lookup failed for http://marc.theaimsgroup.com/?l=pear-dev&m=103134676127239&w=2: Failed to open TCP connection to marc.theaimsgroup.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://marc.theaimsgroup.com/?l=pear-dev&r=1&w=2: Failed to open TCP connection to marc.theaimsgroup.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://marc.theaimsgroup.com/?l=php-cvs&m=102738953806371&w=2: Failed to open TCP connection to marc.theaimsgroup.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://particuliers.edf.fr/: Failed to open TCP connection to particuliers.edf.fr:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://particuliers.edf.fr/rubrique25.html>: bad URI(is not URI?): http://particuliers.edf.fr/rubrique25.html>
[jekyll-webmention_io] Endpoint lookup failed for http://.../rubrique.php3?id_rubrique=43&var_nav_year=2003&var_nav_month=12`: Failed to open TCP connection to ...:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://.../agenda/2003/12/`: bad URI(is not URI?): http://.../agenda/2003/12/`
[jekyll-webmention_io] Endpoint lookup failed for http://www.zebank.com/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.houra.fr/>: bad URI(is not URI?): http://www.houra.fr/>
[jekyll-webmention_io] Endpoint lookup failed for http://whatisthematrix.warnerbros.com/: HTTP redirects too deep
[jekyll-webmention_io] Endpoint lookup failed for http://www.themeatrix.com/>.: bad URI(is not URI?): http://www.themeatrix.com/>.
[jekyll-webmention_io] Endpoint lookup failed for https://services.google.com/tcbin/tc.py?cmd=status: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for https://services.google.com/tc/Welcome.html: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://www.adforum.com/preview/wwd/simple_detail.asp?ID=8427&TDI=AGBTltRh: HTTP redirects too deep
[jekyll-webmention_io] Endpoint lookup failed for http://www.bbdoclick.com/~work/gallery/: Failed to open TCP connection to www.bbdoclick.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.smartpixel.net/chromoweb/fr/index.htm: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://www.blog-and-blues.com/2004/mars/04/Les_Precieuses_Ridicules_ou_Cathos_XHTML_et_CSS.asp: Failed to open TCP connection to www.blog-and-blues.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://gforge.org/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.vasoftware.com/: Failed to open TCP connection to www.vasoftware.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.airbag.ca/archives/002900.php: Failed to open TCP connection to www.airbag.ca:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.airbag.ca/: Failed to open TCP connection to www.airbag.ca:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://alistapart.com/articles/cssdropshadows/: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://en.thinkexist.com/quotes/jeremy_s._anderson/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.retraite.gouv.fr/>: bad URI(is not URI?): http://www.retraite.gouv.fr/>
[jekyll-webmention_io] Endpoint lookup failed for http://www.europe.gouv.fr/>: bad URI(is not URI?): http://www.europe.gouv.fr/>
[jekyll-webmention_io] Endpoint lookup failed for http://www.forums.gouv.fr/>: bad URI(is not URI?): http://www.forums.gouv.fr/>
[jekyll-webmention_io] Endpoint lookup failed for http://www.villette.com/manif/manif.aspx?id=917: Failed to open TCP connection to lavillette.commanif:443 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://gasteroprod.free.fr/>,: bad URI(is not URI?): http://gasteroprod.free.fr/>,
[jekyll-webmention_io] Endpoint lookup failed for http://www.dropload.com/: Failed to open TCP connection to www.dropload.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.lo-w.net/: Failed to open TCP connection to www.lo-w.net:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.cedrichoizey.com/: Failed to open TCP connection to www.cedrichoizey.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://artistes.autoproduction.net/lo_et_cedric_hoizey: Failed to open TCP connection to artistes.autoproduction.net:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.lo-w.net/>: bad URI(is not URI?): http://www.lo-w.net/>
[jekyll-webmention_io] Endpoint lookup failed for http://www.cedrichoizey.com/>: bad URI(is not URI?): http://www.cedrichoizey.com/>
[jekyll-webmention_io] Endpoint lookup failed for http://www.bm-chambery.fr/services/deficients.htm: Failed to open TCP connection to www.lebouquetdesbibliotheques.frservices:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://ftp.eu.mozilla.org/pub/mozilla.org/firefox/releases/1.0/win32/fr-FR/Firefox%20Setup%201.0.exe: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://www.dailymotion.com/embed/video/x9k93: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.horrible.demon.co.uk/die_peacefully_in_my_sleep.htm: Failed to open TCP connection to www.horrible.demon.co.uk:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.mojombo.com/archives/000054.html: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.gasteroprod.com/rss/themes/spip/29.rss>: bad URI(is not URI?): http://www.gasteroprod.com/rss/themes/spip/29.rss>
[jekyll-webmention_io] Endpoint lookup failed for http://www.gasteroprod.com/design/backend_theme.html>: bad URI(is not URI?): http://www.gasteroprod.com/design/backend_theme.html>
[jekyll-webmention_io] Endpoint lookup failed for http://www.gasteroprod.com/rss/commentaires/pompez-428.rss>: bad URI(is not URI?): http://www.gasteroprod.com/rss/commentaires/pompez-428.rss>
[jekyll-webmention_io] Endpoint lookup failed for http://www.gasteroprod.com/design/backend_commentaires.html>: bad URI(is not URI?): http://www.gasteroprod.com/design/backend_commentaires.html>
[jekyll-webmention_io] Endpoint lookup failed for http://www.blogaid.org.uk/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.pierrecarion.com/: Failed to open TCP connection to www.pierrecarion.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.pierrecarion.com/blog/archives/2005/01/03/2057.html: Failed to open TCP connection to www.pierrecarion.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://tiscali.fr/: Failed to open TCP connection to tiscali.fr:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://bettersearch.g-blog.net/: Net::OpenTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://pl.clever-age.com/: Failed to open TCP connection to pl.clever-age.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://stephane.etsoncar.net/news/58.shtml: Failed to open TCP connection to stephane.etsoncar.net:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.ludicorp.com/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://tech.irt.org/articles/js173/: Failed to open TCP connection to tech.irt.org:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://flickrate.gasteroprod.com/: Failed to open TCP connection to flickrate.gasteroprod.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://flickrate.gasteroprod.com/browse.php?nb=32&who=all&when=all&criteria=aesthetics: Failed to open TCP connection to flickrate.gasteroprod.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://flickrate.gasteroprod.com/register.php: Failed to open TCP connection to flickrate.gasteroprod.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://flickrate.gasteroprod.com/tools.php: Failed to open TCP connection to flickrate.gasteroprod.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://flickrate.gasteroprod.com/browse.php?nb=32&who=you&when=all&criteria=aesthetics: Failed to open TCP connection to flickrate.gasteroprod.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://flickrate.gasteroprod.com/browse.php?nb=32&who=others&when=all&criteria=aesthetics: Failed to open TCP connection to flickrate.gasteroprod.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.geobloggers.com/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.geobloggers.com/index.cfm?lat=40&lon=10&username=Nicolas+Hoizey&range=180&t=k: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.geobloggers.com/index.cfm?lat=40&lon=-85&username=Nicolas+Hoizey&range=180&t=k: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.spreadfirefox.com/?q=node/view/16956: Failed to open TCP connection to www.spreadfirefox.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.summer-refresh-05.com/: Failed to open TCP connection to www.summer-refresh-05.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://flickrate.gasteroprod.com/: Failed to open TCP connection to flickrate.gasteroprod.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.clever-age.com/actualites/petits-dejeuners/jusqu-aller-avec-logiciel-libre-retours-experiences-perspectives-416.html: Failed to open TCP connection to fr:443 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.gasteroprod.com/>,: bad URI(is not URI?): http://www.gasteroprod.com/>,
[jekyll-webmention_io] Endpoint lookup failed for http://6v8.gamboni.org/test-aig/agenda.php: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://userscripts.org/scripts/show/786: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://del.icio.us/: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://userscripts.org/scripts/show/2243: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://userscripts.org/scripts/show/2243: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://flickrate.gasteroprod.com/: Failed to open TCP connection to flickrate.gasteroprod.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://flickrate.gasteroprod.com/most_favored.php: Failed to open TCP connection to flickrate.gasteroprod.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://labs.systemone.at/retrievr/about: Failed to open TCP connection to labs.systemone.at:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://feedlounge.com/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.bloglines.com/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://feedlounge.com/blog/2006/01/16/public-release/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://feedlounge.com/support/tutorial/subscribe/?pagename=support/faq/tutorial/subscribe/&page=: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://feedlounge.com/support/tutorial/read/?pagename=support/faq/tutorial/read/&page=: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://feedlounge.com/support/faq/feedlounge/keyboard-shortcuts/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://feedlounge.com/support/tutorial/tags/?pagename=support/faq/tutorial/tags/&page=: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://forums.feedlounge.com/viewtopic.php?id=23: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://forums.feedlounge.com/viewtopic.php?id=356: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://feedlounge.com/blog/2006/01/09/pricing-payments/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://feedlounge.com/register/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://userscripts.org/scripts/show/2662: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://today.reuters.fr/news/newsArticle.aspx?type=technologyNews&storyID=2006-01-20T112219Z_01_MAL040916_RTRIDST_0_OFRIN-SONY-PHOTO-20060120.XML: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.nomatica.fr/photo/kd400zFR.htm: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://64.124.231.223/avatar.php?gravatar_id=9aa2aa68144b2781ac025a29c83bbdd4&size=42&rating=PG: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.integration.fr/: Failed to open TCP connection to www.integration.fr:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.clever-age.com/actualites/agenda/forum-integration-criteres-choix-positionnement-principaux-outils-eai-esb-etl-eip-autres-solutions-integration-439.html: Failed to open TCP connection to fr:443 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.bloglines.com/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.clever-age.com/actualites/petits-dejeuners/paris-etat-art-outils-collaboratif-422.html: Failed to open TCP connection to fr:443 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://alexadex.com/ad/about: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://alexadex.com/ad/url/gasteroprod.com: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://www.webmastereyes.com/: Failed to open TCP connection to www.webmastereyes.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.webmastereyes.com/index.php?url=http://www.gasteroprod.com/: Failed to open TCP connection to www.webmastereyes.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://feeds.feedburner.com/GasteroProd>: bad URI(is not URI?): http://feeds.feedburner.com/GasteroProd>
[jekyll-webmention_io] Endpoint lookup failed for http://www.userscript.com/scripts/show/4104: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://microsoft.brainsonic.com/customers/microsoft/20060427/Steve_Ballmer_VO/files/demo.htm?Media=5: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://sessions.mix06.com/view.asp?sessionChoice=2000&disc=&pid=BTB033&yearChoice=2005: Failed to open TCP connection to sessions.mix06.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.damienanfroy.net/index.php?2006/05/02/40-compte-rendu-du-mix06-paris: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://bourse.tf1.fr/detail_actualite.phtml?news=3508959: Failed to open TCP connection to bourse.lci.frdetail_actualite.phtml:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.identity20.com/media/OSCON2005/: Failed to open TCP connection to dickhardt.orgmedia:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.vnunet.fr/actualite/tpepme_-_business/strategies_et_marches/20060706006: Failed to open TCP connection to www.vnunet.fr:80 (Connection refused - connect(2) for "www.vnunet.fr" port 80)
[jekyll-webmention_io] Endpoint lookup failed for http://www.vnunet.com/vnunet/news/2159846/microsoft-flip-flops-odf: Failed to open TCP connection to www.vnunet.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.clever-age.com.pl/: Failed to open TCP connection to www.clever-age.com.pl:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for https://www.cashstore.fr/: SSL_connect returned=1 errno=0 state=error: certificate verify failed
[jekyll-webmention_io] Endpoint lookup failed for https://www.cashstore.fr/signup/signup1.aspx: SSL_connect returned=1 errno=0 state=error: certificate verify failed
[jekyll-webmention_io] Endpoint lookup failed for http://www.amazon.com/S3-AWS-home-page-Money/b/ref=sc_fe_l_2/104-0339411-7512773?ie=UTF8&node=16427261&no=3435361&me=A36L942TSJ2AJA: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://www.jungledisk.com/: Net::OpenTimeout
[jekyll-webmention_io] Endpoint lookup failed for https://mozy.com/?ref=VH5M5G: Net::OpenTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://www.glagla.org/blog/index.php/2007/05/05/178-mozy-j-ai-teste-pour-vous: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.gldatasystems.fr/apple2007/form/gp.aspx?culture=US&l=1F86174NB2: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.hchamp.com/: Failed to open TCP connection to www.hchamp.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.clio.renault-sport.com/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.apple.com/iphone/: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://www.apple.com/: Net::OpenTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://www.petranemcova.org/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.clever-age.com/veille/blog/comment-definir-dans-jquery-ses-propres-filtres-de-selection.html: Net::OpenTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://www.ugobe.com/: Failed to open TCP connection to www.ugobe.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://store.ugobe.com/: Failed to open TCP connection to store.ugobe.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.blu-ray.sony-europe.com/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.blu-ray.sony-europe.com/player/player.php?lang=fr: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.apple.com/environment/: Net::OpenTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://www.apple.com/ilife/iphoto/: HTTP redirects too deep
[jekyll-webmention_io] Endpoint lookup failed for http://www.vdirectce.com/ecommerce.php?pg=catalogue&cid=16: Failed to open TCP connection to www.vdirectce.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://browser/skin/bookmark-hover-mid.png: Failed to open TCP connection to browser:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://browser/skin/bookmark-open-mid.png: Failed to open TCP connection to browser:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://B_sites>: bad URI(is not URI?): http://B_sites>
[jekyll-webmention_io] Endpoint lookup failed for http://jyte.com/cl/flickr-should-provide-rss-feeds-for-favorites: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://pipes.yahoo.com/: Failed to open TCP connection to pipes.yahoo.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://pipes.yahoo.com/: Failed to open TCP connection to pipes.yahoo.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://pipes.yahoo.com/nicolashoizey/gasteroprod: Failed to open TCP connection to pipes.yahoo.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://pipes.yahoo.com/nicolashoizey/feeditemprefix: Failed to open TCP connection to pipes.yahoo.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://feeds.feedburner.com/GasteroProd>: bad URI(is not URI?): http://feeds.feedburner.com/GasteroProd>
[jekyll-webmention_io] Endpoint lookup failed for http://feeds.feedburner.com/GasteroProd/Blog>: bad URI(is not URI?): http://feeds.feedburner.com/GasteroProd/Blog>
[jekyll-webmention_io] Endpoint lookup failed for http://feeds.feedburner.com/GasteroProd/Photos>: bad URI(is not URI?): http://feeds.feedburner.com/GasteroProd/Photos>
[jekyll-webmention_io] Endpoint lookup failed for http://feeds.feedburner.com/GasteroProd/Liens>: bad URI(is not URI?): http://feeds.feedburner.com/GasteroProd/Liens>
[jekyll-webmention_io] Endpoint lookup failed for http://userscripts.org/scripts/show/1378: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://6v8.gamboni.org/Flickr-Buddy-Interestingness.html?lang=fr: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://userscripts.org/scripts/show/1543: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://userscripts.org/scripts/show/5346: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://6v8.gamboni.org/Flickr-More-info-in-mails.html: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://6v8.gamboni.org/Flickr-Add-referer-into-comments.html: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://6v8.gamboni.org/Flickr-Pool-Date.html: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://userscripts.org/scripts/show/10382: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://googledocs.blogspot.com/: HTTP redirects too deep
[jekyll-webmention_io] Endpoint lookup failed for http://www.ten.fr/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.ten.fr/telephone_details.php?id=12030918074022: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.ten.fr/services_ten.php: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://wiki.ten.fr/wiki/index.php?title=Internet: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://iwi.lebardegandi.net/post/2008/05/21/Le-filer-13-%3A-Epilogue: Failed to open TCP connection to iwi.lebardegandi.net:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://groups.gandi.net/fr/topic/gandi.fr.hebergement.expert/15410: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://del.icio.us/nhoizey: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://case.oncle-tom.net/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://case.oncle-tom.net/2008/07/23/conventions-de-programmation-necessaire-maturite/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://fr.comp.internet.www.auteurs.php: Failed to open TCP connection to fr.comp.internet.www.auteurs.php:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://fr.comp.lang.php: Failed to open TCP connection to fr.comp.lang.php:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.glagla.org/weblog/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.cuil.com/: Failed to open TCP connection to www.cuil.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.polarrose.com/: Failed to open TCP connection to www.polarrose.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://eeepc.asus.com/fr/index.htm: Failed to open TCP connection to eeepc.asus.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://descary.com/feedburner-integre-a-google-rien-ne-va-plus/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://pipes.yahoo.com/: Failed to open TCP connection to pipes.yahoo.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://pipes.yahoo.com/nicolashoizey: Failed to open TCP connection to pipes.yahoo.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.happy-iphone.com/applications/musique/remote-pour-piloter-itunes-et-apple-tv-depuis-un-iphone: Failed to open TCP connection to www.happy-iphone.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://decimus.net/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.splitgames.fr/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://blog.splitgames.fr/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.blog-and-blues.org/articles/Les_syntaxes_de_commentaires_conditionnels_pour_IE_Windows: Failed to open TCP connection to www.blog-and-blues.org:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://flic.kr/p/5Z9uNn>.: bad URI(is not URI?): http://flic.kr/p/5Z9uNn>.
[jekyll-webmention_io] Endpoint lookup failed for http://flic.kr/nicolas-hoizey/>: bad URI(is not URI?): http://flic.kr/nicolas-hoizey/>
[jekyll-webmention_io] Endpoint lookup failed for http://userscripts.org/scripts/show/40582: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://3slips.fr/: Failed to open TCP connection to 3slips.fr:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.jpgmag.com/photos/809995>.: bad URI(is not URI?): http://www.jpgmag.com/photos/809995>.
[jekyll-webmention_io] Endpoint lookup failed for http://digg.com/arts_culture/Fluorescent_Jellyfishes>: bad URI(is not URI?): http://digg.com/arts_culture/Fluorescent_Jellyfishes>
[jekyll-webmention_io] Endpoint lookup failed for http://www.comantes.com: Failed to open TCP connection to www.comantes.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://W3C//DTD: Failed to open TCP connection to W3C:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://EN: Failed to open TCP connection to EN:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://www.tequilas-secrets.com/?2008/06/02/819-photographier-un-orage-enfin-les-eclairs: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.tequilas-secrets.com/?2009/05/25/1290-pour-une-nuit-avec-toi: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://case.oncle-tom.net/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://userscripts.org/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://h10010.www1.hp.com/wwpc/fr/fr/sm/WF05a/321957-321957-64295-3955550-3955550-4094022.html: HTTP redirects too deep
[jekyll-webmention_io] Endpoint lookup failed for http://500px.com/photo/341000: Net::OpenTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://fr.wikipedia.org/wiki/Internet_Explorer: Net::OpenTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://googleenterprise.blogspot.com/2010/01/modern-browsers-for-modern-applications.html: HTTP redirects too deep
[jekyll-webmention_io] Endpoint lookup failed for http://twtpoll.com/xvt5wp>: bad URI(is not URI?): http://twtpoll.com/xvt5wp>
[jekyll-webmention_io] Endpoint lookup failed for http://fireeagle.yahoo.net/: Failed to open TCP connection to fireeagle.yahoo.net:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://browsersize.googlelabs.com/: Failed to open TCP connection to browsersize.googlelabs.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://tickets.web-ux.org/: Failed to open TCP connection to tickets.web-ux.org:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://tickets.web-ux.org/cms.php?id_cms=8: Failed to open TCP connection to tickets.web-ux.org:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://tickets.web-ux.org/cms.php?id_cms=10: Failed to open TCP connection to tickets.web-ux.org:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://tickets.web-ux.org/product.php?id_product=11: Failed to open TCP connection to tickets.web-ux.org:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://tickets.web-ux.org/product.php?id_product=13: Failed to open TCP connection to tickets.web-ux.org:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.clever-age.com/veille/blog/sud-web-et-webux-le-web-d-aujourd-hui-a-la-portee-du-soleil.html: HTTP redirects too deep
[jekyll-webmention_io] Endpoint lookup failed for http://www.cdiscount.com/electromenager/machines-a-coudre/singer/f-107092205-qa988ea.html>: bad URI(is not URI?): http://www.cdiscount.com/electromenager/machines-a-coudre/singer/f-107092205-qa988ea.html>
[jekyll-webmention_io] Endpoint lookup failed for http://www.liberation.fr/societe/01012383917-les-francais-inquiet-de-l-augmentation-du-prix-des-fraises>: bad URI(is not URI?): http://www.liberation.fr/societe/01012383917-les-francais-inquiet-de-l-augmentation-du-prix-des-fraises>
[jekyll-webmention_io] Endpoint lookup failed for http://www.tourmag.com/perte-du-tripple-a-naufrage-de-la-france_a49271.html>: bad URI(is not URI?): http://www.tourmag.com/perte-du-tripple-a-naufrage-de-la-france_a49271.html>
[jekyll-webmention_io] Endpoint lookup failed for http://www.liberation.fr/societe/01012383917-les-francais-inquiet-de-l-augmentation-des-frais-de-sante>: bad URI(is not URI?): http://www.liberation.fr/societe/01012383917-les-francais-inquiet-de-l-augmentation-des-frais-de-sante>
[jekyll-webmention_io] Endpoint lookup failed for http://wiki.alwaysdata.com/wiki/Activer_une_extension_PHP_pr%C3%A9-install%C3%A9e: URI must be ascii only "https://help.alwaysdata.com/wiki/Activer_une_extension_PHP_pr\xC3\xA9-install\xC3\xA9e"
[jekyll-webmention_io] Endpoint lookup failed for http://gasteroprod.com/](http://gasteroprod.com/: bad URI(is not URI?): http://gasteroprod.com/](http://gasteroprod.com/
[jekyll-webmention_io] Endpoint lookup failed for http://www.gasteroprod.com/](http://www.gasteroprod.com/: bad URI(is not URI?): http://www.gasteroprod.com/](http://www.gasteroprod.com/
[jekyll-webmention_io] Endpoint lookup failed for http://fnac.fr/](http://fnac.fr/: bad URI(is not URI?): http://fnac.fr/](http://fnac.fr/
[jekyll-webmention_io] Endpoint lookup failed for http://www.fnac.com/](http://www.fnac.com/: bad URI(is not URI?): http://www.fnac.com/](http://www.fnac.com/
[jekyll-webmention_io] Endpoint lookup failed for http://fontdeck.com/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.codestyle.org/css/font-family/sampler-CombinedResultsFull.shtml: Failed to open TCP connection to www.codestyle.org:80 (Connection refused - connect(2) for "www.codestyle.org" port 80)
[jekyll-webmention_io] Endpoint lookup failed for http://www.linotype.com/1116/aboutthefont.html: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://www.clever-age.com/veille/reactions/pagespeed-et-yslow-ne-sont-pas-des-indices-de-performance.html: HTTP redirects too deep
[jekyll-webmention_io] Endpoint lookup failed for http://leverestdanslapomme.tumblr.com/](http://leverestdanslapomme.tumblr.com/: bad URI(is not URI?): http://leverestdanslapomme.tumblr.com/](http://leverestdanslapomme.tumblr.com/
[jekyll-webmention_io] Endpoint lookup failed for http://romy.tetue.net/stop-arial-11px: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://blog.temesis.com/post/2009/09/21/lacher-prise: Failed to open TCP connection to blog.temesis.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for https://revocation-report.x509labs.com: Failed to open TCP connection to revocation-report.x509labs.com:443 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for https://aws.amazon.com/fr/cloudfront/pricing/: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://blog.tutorspree.com/post/54349646327/death-of-organic-search: Failed to open TCP connection to blog.tutorspree.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://elecson.com/: Net::ReadTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://lecercle.lesechos.fr/entreprises-marches/services/distribution/221150611/web-to-store-monde-parle: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.spip.net/: Net::OpenTimeout
[jekyll-webmention_io] Endpoint lookup failed for http://pico.dev7studios.com/: Failed to open TCP connection to pico.dev7studios.com:80 (Connection refused - connect(2) for "pico.dev7studios.com" port 80)
[jekyll-webmention_io] Endpoint lookup failed for http://blog.pukhalski.com/: Failed to open TCP connection to blog.pukhalski.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Endpoint lookup failed for http://www.chassimages.com/index.php?mact=News,cntnt01,detail,0&cntnt01articleid=103&cntnt01returnid=58: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.chassimages.com/forum/index.php/topic,192711.0.html: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.chassimages.com/forum/index.php/topic,192711.msg4164695.html: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.chassimages.com/forum/index.php/topic,192711.msg4175016.html: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://www.nikon-school.fr/: SSL_connect returned=1 errno=0 state=error: certificate verify failed
[jekyll-webmention_io] Endpoint lookup failed for https://particuliers.secure.lcl.fr/PSP/nouveautes-espace-gestion/Ressources/Gemc/StyleSheet/Ressources/Gemc/Images/NewsCli/bkg-bas.jpg`: bad URI(is not URI?): https://particuliers.secure.lcl.fr/PSP/nouveautes-espace-gestion/Ressources/Gemc/StyleSheet/Ressources/Gemc/Images/NewsCli/bkg-bas.jpg`
[jekyll-webmention_io] Endpoint lookup failed for https://particuliers.secure.lcl.fr/PSP/nouveautes-espace-gestion/Ressources/Gemc/Images/NewsCli/bkg-bas.jpg`: bad URI(is not URI?): https://particuliers.secure.lcl.fr/PSP/nouveautes-espace-gestion/Ressources/Gemc/Images/NewsCli/bkg-bas.jpg`
[jekyll-webmention_io] Endpoint lookup failed for https://oncletom.io/: execution expired
[jekyll-webmention_io] Endpoint lookup failed for http://t.co/auySzsEfSB</a></p>&mdash;: bad URI(is not URI?): http://t.co/auySzsEfSB</a></p>&mdash;
[jekyll-webmention_io] Endpoint lookup failed for https://twitter.com/nhoizey: Net::OpenTimeout
[jekyll-webmention_io] Endpoint lookup failed for https://t.co/evL9he9fw1</a>: bad URI(is not URI?): https://t.co/evL9he9fw1</a>
[jekyll-webmention_io] Endpoint lookup failed for https://t.co/V5XiS7991g</a>: bad URI(is not URI?): https://t.co/V5XiS7991g</a>
[jekyll-webmention_io] Endpoint lookup failed for http://workshops.flou-sentimental.com/: Failed to open TCP connection to workshops.flou-sentimental.com:80 (getaddrinfo: nodename nor servname provided, or not known)
[jekyll-webmention_io] Sending webmention of https://adactio.com/journal/7698 in https://nicolas-hoizey.com/2014/11/suggestions-de-sujets-et-orateurs-pour-paris-web-2015.html
[jekyll-webmention_io] Webmention successful!
jekyll 3.5.1 | Error:  765: unexpected token at ''
```

Maybe it would be nice to have logs for success also, because I don't know if any worked.

**Comment by nhoizey** [comment]
Oh, in fact the last one, just before the error, succeeded, it seems!

**Comment by aarongustafson** [comment]
:-)

Can you trace that command once more? I'm curious about that final error.

**Comment by nhoizey** [comment]
I'm now on holyday, but I'll try. Is there a risk I send a Webmention to Jeremy again?

**Comment by aarongustafson** [comment]
It shouldn't. The Webmention is logged to a YAML file as sent.

**Comment by aarongustafson** [comment]
Tested as working on my end. Fixed in 2.6.4.

**Comment by nhoizey** [comment]
@aarongustafson I still get the error with current master.

Here is just the end of the log:

```
…
[jekyll-webmention_io] Could not find a webmention endpoint at https://twitter.com/adactio
[jekyll-webmention_io] Sending webmention of https://adactio.com/journal/7698 in https://nicolas-hoizey.com/2014/11/suggestions-de-sujets-et-orateurs-pour-paris-web-2015.html
[jekyll-webmention_io] Webmention successful!
bundler: failed to load command: jekyll (/Users/nhoizey/.rvm/gems/ruby-2.4.0/bin/jekyll)
JSON::ParserError: 765: unexpected token at ''
  /Users/nhoizey/.rvm/gems/ruby-2.4.0@global/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0@global/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-webmention_io-ecdc71e7d530/lib/jekyll/commands/webmention.rb:33:in `block (2 levels) in process'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-webmention_io-ecdc71e7d530/lib/jekyll/commands/webmention.rb:24:in `each'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-webmention_io-ecdc71e7d530/lib/jekyll/commands/webmention.rb:24:in `block in process'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-webmention_io-ecdc71e7d530/lib/jekyll/commands/webmention.rb:23:in `each'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-webmention_io-ecdc71e7d530/lib/jekyll/commands/webmention.rb:23:in `process'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-webmention_io-ecdc71e7d530/lib/jekyll/commands/webmention.rb:11:in `block (2 levels) in init_with_program'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/exe/jekyll:13:in `<top (required)>'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bin/jekyll:22:in `load'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bin/jekyll:22:in `<top (required)>'
```

**Comment by aarongustafson** [comment]
Fixed in 2.8.2

**Comment by nhoizey** [comment]
Great, thanks!
